name: certificate_generator
description: Certificate Generator.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  spreadsheet_decoder: # parsing xlsx files
  path_provider: # reading/writing files in application document directory
  file_picker: # using local files from device
  pdf_viewer_plugin: # viewing pdf files
  pdf:
  permission_handler: # handling runtime permissions
  share_extend: # sharing files
  provider: # state-management
  printing: # using image assets in pdf generation
  open_file: ^3.0.1
  flutter_local_notifications: ^2.0.0+1
  screenshot: ^0.2.0
  firebase_core:
  firebase_auth: ^0.14.0+5
  firebase_dynamic_links: ^0.5.1
  firebase_storage: ^3.0.3
  qr_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/account.png
    - assets/images/temp.png
    - assets/images/cert.jpeg
    - assets/